name: "[CI] Admin"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-admin/**"
      - "decidim-core/**"
      - "decidim-dev/**"
      - "decidim-participatory_processes/**"

env:
  CI: "true"
  SIMPLECOV: "true"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ./.github/actions/module-rspec
        with:
          name: decidim-admin